### ISSUE TITLE
Project reading in dev

### ISSUE THREAD

**Issue by jwindha1** [easybase/easybase-react#2]
I'm new to javascript and easybase, and I'm implementing a project using several tables and users. I can write to a table using `addRecord` or `Frame().push` but then always get back an empty `Frame` or a frame with just the newest element respectively. The table has read/write permissions for the user in the project settings, so it seems like writing works fine but reading does not. I'm working in dev on localhost and I'm wondering if this is because there's an option to make an integration "testing mode enabled" for a table but not for the whole project. Any ideas for how to work with or around this? Thanks.

Specifics:

My table `"FEELINGS"` currently has many rows and appears on https://app.easybase.io/#/tables as such. My constant `row` is a `Record` which contains a key-value pair `location: "beginning"`. This code is within an async function called when a user clicks "save", and the user is signed in:
```
configureFrame( {tableName: "FEELINGS"} )
await sync()
await addRecord({
            insertAtEnd: true,
            newRecord: row,
            tableName: "FEELINGS"
        })
await sync()
console.log(Frame().map(e => e.location))
```
The log is `Frame:  []`.

If I replace the code as such:
```
configureFrame( {tableName: "FEELINGS"} )
await sync()
Frame().push(row)
await sync()
console.log(Frame().map(e => e.location))
```
The log is `Frame:  ["beginning"]`, so it now contains the pushed item but not any others.

**Comment by dilan-dio4** [comment]
Hello,

If you're using a project and have enabled a table's permissions in the project menu, you don't need to make a table-specific React integration. So, you can safely delete those without loosing access from your code.

From there, I think the issue might be that you're accessing **Frame()** before it's updated. **sync()** does not return after the new Frame has been configured, it returns after the networking functions are complete. The **useFrameEffect()** hook is  used for dealing with your newly updated **Frame()**. So, try something like the following code snippet. Let me know if this helps!

```jsx
const {
  configureFrame,
  sync,
  Frame,
  isUserSignedIn,
  addRecord,
  useFrameEffect
} = useEasybase();

useFrameEffect(() => {
  console.log(Frame().map(e => e.location))
});

const clickedButton = async (res) => {
  if (isUserSignedIn()) {
    await addRecord({
      insertAtEnd: true,
      newRecord: row,
      tableName: "FEELINGS"
    })

    configureFrame( {tableName: "FEELINGS"});
    sync();
  }
}
```

**Comment by jwindha1** [comment]
Thanks so much! This helps me understand a lot better. Based on this, it seems like I'm having issues in general reading information with `Frame`: currently on the web app I can check that I've written several rows of data to my table `"FEELINGS"`, and I get successful message responses when I write to it, but a call to `Frame()` always returns an empty list. 

```
if (!configureFrame({ tableName: "FEELINGS" }).success) {
    console.log("failed to configure frame")
}
if (!(await sync()).success) { console.log("failed to sync") }

console.log(Frame())
console.log(Frame().map(e => e.location))
```
Console logs:
```
Proxy {Symbol(observable-meta-key): x, observe: ƒ, unobserve: ƒ}
[[Handler]]: x
[[Target]]: Array(0)
[[IsRevoked]]: false
```
```
[]
```

I thought maybe the issue was with the existing records in my table not being accessed because of a user authentication problem, but I changed my project permissions to universal read access and universal write access, and I got the same result. Any ideas? 

A few other miscellaneous notes (I'm new to using Issues so I'm not sure of what the best format is to ask about these -- sorry for a very long post): 
- I've adjusted my project to be almost entirely write-only due to the above problem, but I'm now trying to use `updateRecordImage` to add an image and it's giving me this error with this code (with both the commented and uncommented versions of `imgRecord`). So, this is the more relevant use case for me now -- unsure if it has the same underlying problem as above or not. 
  ```
  if (isUserSignedIn()) {
      if (!configureFrame({ tableName: "METADATA" }).success) {
          console.log("failed to configure frame")
      }
      if (!(await sync()).success) { console.log("failed to sync") }
      const imgRecord = Frame().filter(e => e.name == "participant-img")[0]  // this is undefined due to the above issue even though there exists a record matching this
      // const imgRecord = { name: "participant-img" }
      const record = {
          attachment: participantImg,
          columnName: "img",
          record: imgRecord,
          tableName: "METADATA"
      }
      if (!(await updateRecordImage(record)).success) {
          console.log("failed to add bio image record, trying again...")
          console.log(await updateRecordImage(record))
      }
      if (!(await sync()).success) { console.log("failed to sync") }
  }
  ```
  ```
  failed to add bio image record, trying again...
  {success: false, message: "Attempting to add attachment to a new record that has not been synced. Please sync() before trying to add attachment."}
  ```

- Overall I've noticed that I get a network error when I try to add a record to an empty table. I've been circumventing this by adding a row manually in the app to each table, so it's not a big issue but a potential bug. Here's the errror:
  ```
  {message: TypeError: Network request failed
      at XMLHttpRequest.xhr.onerror (http://localhost:3000/static/j…, success: false}
  message: TypeError: Network request failed at XMLHttpRequest.xhr.onerror (http://localhost:3000/static/js/vendors~main.chunk.js:1061:20)
  message: "Network request failed"
  stack: "TypeError: Network request failed↵    at XMLHttpRequest.xhr.onerror (http://localhost:3000/static/js/vendors~main.chunk.js:1061:20)"
  __proto__: Error
  success: false
  __proto__: Object
  ```

- I would like to be able to export tables from the web app based on user, but user id information is not included in exports: is there a way to do this? 

Thanks for your patience and help!

**Comment by dilan-dio4** [comment]
Okay I think I have some solutions for the problems you're facing here.

**First, install the latest version of this package with `npm install easybase-react`**. This should resolve the image uploading image you were facing.

Following that, move the these two lines:
```jsx
console.log(Frame())
console.log(Frame().map(e => e.location))
```

to the `useFrameEffect()` hook like so:
```jsx
function MyComponent(props){
  const { configureFrame, sync, Frame, useFrameEffect } = useEasybase();

  const someoneClickedButton () => {
    if (!configureFrame({ tableName: "FEELINGS" }).success) {
        console.log("failed to configure frame")
    }
    if (!(await sync()).success) { console.log("failed to sync") }
  }

  useFrameEffect(() => {
    console.log(Frame().map(e => e.location))
  })

  return (
    //...
  )
}
```

Calling `sync()` changes your `Frame` which triggers the `useFrameEffect` hook.

Let me know if these solutions fix some some of the issues you were facing. Thanks!

**Comment by eleanorlakeh** [comment]
Hi - I'm having the same issue, were you able to resolve it? I'm able to write to my table but not read from it. (Write and read are both enabled in the table settings.) `Frame()` is empty, and `useFrameEffect()` is never called. Any troubleshooting tips @dilan-dio4? Thanks!

```
function App() {
  const { Frame, configureFrame, sync, useFrameEffect } = useEasybase();

  useEffect(() => {
    configureFrame({ tableName: "RECIPES" });
    sync();
  }, [configureFrame, sync]);

  useFrameEffect(() => {
    console.log("useFrameEffect called");
    console.log(Frame().map(e => e.location))
  })

  return (
    <EasybaseProvider ebconfig={ebconfig}>
      <div className="AppContainer">
          <div className="App">
            {Frame().map((r) => (
              <Recipe name={r.name} link = {r.link} description = {r.description} />
            ))}
          </div>
      </div>
    </EasybaseProvider>
  );
}
```
